### ISSUE TITLE
Formatting Errors

### ISSUE THREAD

**Issue by KingPixil** [talonbragg/talonbragg.com---OLD#5]
Hey @pvpgamecrash 

You have a lot of formatting errors in your code. I'll try to list them all here:
## index.html

Here are some errors in your `index.html` file:
- `<style>` is a descendant of `<html>`
-  the `<script>` pointing to JQuery is a descendant of `<html>`
-  `<div>` is a descendant of `<html>`
- Redundant inline styles in `body`
- Menu uses Unicode, use CSS instead
- `<center>` is obsolete in HTML5, use appropriate CSS instead
- `height: = 100`
- `<br>` should not be used to make space, use appropriate CSS instead
- Complete mess of `<style>` and `<script>` in the bottom
## Blog
- Just a copy of a Start Bootstrap theme
- Plagiarized posts
## Featured
- Just a copy of Codyhouse's demo
- Doesn't make sense
- Uses SCSS, which requires a custom Sass preprocessor, which requires you to use Ruby, which is dynamic/backend, not supported on Github Pages
## Stylesheets
- Has .zip files, almost no actual custom stylesheets, most of your styles are inline (very inefficient)
- Just lots of libraries
## Breakout
- Copy of MDN's tutorial, no credit given
## React.js
- Should be used to host Facebook's React library
- Uses Node.js, which is backend/server side and cannot be run via Github Pages
- No point in having it
- No package.json
- Your website doesn't require React, it's not a dynamic MVC one page app
## params.json
- Not required as you don't use a static site generator
- Pointless

That's the gist of it, and it only includes major errors, the whole file structure is so hard to understand, you might want to start from scratch. Also, most of this is just a template in which you added your own text, just bits of code **copied** from sources combined into one, unformatted, inefficient blob.

You might want to actually try learning, instead of copying, it's not a good way of getting into the developer community.

**Comment by NightStalkers** [comment]
Bro, I copied snippets of code from RipOff Games...

**Comment by NightStalkers** [comment]
@KingPixil 

"`<center>` is obsolete in html, use appropriate css instead"

In most cases, `<center>` and `</center>` tags are better for formatting because they are HTML tags.

Instead of scrolling down to your css or visiting a linked file,  you can wrap HTML around a `<center>` tag and be done w/ it

**Comment by NightStalkers** [comment]
If you want us to give credit, just say so.

You don't have to type a long MarkDown comment

**Comment by NightStalkers** [comment]
##BTW

react.js was just a test

Since GitHub doesn't have a React Compiler, it's pointless

**Comment by KingPixil** [comment]
Ok, you might want to improve the code then, I typed the long comment to let you know some things you should fix, never wanted to come across as annoying :smile: I just wanted to help out a little.

You really should make a CSS class, I wrote a [blog post](http://blog.kabir.ml/posts/centering-in-css) on this, `<center>` is not supported in HTML5, you shouldn't use it **at all**. See [this link](http://www.w3schools.com/tags/tag_center.asp).
